#spring.datasource.url =jdbc:mysql://localhost:3306/couponify?useSSL=false&serverTimezone=UTC
#spring.datasource.username= root
#spring.datasource.password = RadisysRadisys@2895
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
#app.jwt-secret = JWTSecretKey
#app.jwt-expiration-millisecond = 604800000
  #60000 1min
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
    profiles:
        active: prod

app:
  auth:
    tokenSecret: JWTSecretKey
    tokenExpirationMsec: 604800000

  cors:
    allowedOrigin: https://couponifyapp-env.eba-ajqqd26a.us-east-1.elasticbeanstalk.com/ http://couponifyapp-env.eba-ajqqd26a.us-east-1.elasticbeanstalk.com/

  oauth2:
    authorizedRedirectUris:
      - http://couponifyapp-env.eba-ajqqd26a.us-east-1.elasticbeanstalk.com/oauth2/redirect
      - http://couponifyapp-env.eba-ajqqd26a.us-east-1.elasticbeanstalk.com/redirect-uri
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect


